CREATE OR REPLACE PROCEDURE BL_CL.LOAD_CE_STORES()
LANGUAGE PLPGSQL
AS $$
DECLARE ROWS_INSERTED INTEGER:=0;
BEGIN
	with all_stores as( SELECT DISTINCT 
       "STORE_ID",
       "STORE_ADDRESS",
       "STORE_TYPE",
       "STORE_DESC",
	     "WEBSITE",
       "STORE_CITY",
       "STORE_COUNTRY",
		   "EVENT_DT",
       'SA_ONLINE_SALES' AS "SOURCE_SYSTEM",
       'SRC_ONLINE_COFFEE_SHOP_TRANSACTIONS' AS "SOURCE_ENTITY"
    FROM SA_ONLINE_SALES.SRC_ONLINE_COFFEE_SHOP_TRANSACTIONS
    UNION ALL
    SELECT DISTINCT 
       "STORE_ID",
       "STORE_ADDRESS",
       "STORE_TYPE",
       "STORE_DESC",
	     'n.a.' as "WEBSITE",
       "STORE_CITY",
       "STORE_COUNTRY",
		   "EVENT_DT",
       'SA_OFFLINE_SALES' AS "SOURCE_SYSTEM",
       'SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS' AS "SOURCE_ENTITY"
    FROM SA_OFFLINE_SALES.SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS),
latest_stores as (select *, row_number() over(partition by "STORE_ID","SOURCE_SYSTEM","SOURCE_ENTITY" ORDER BY "EVENT_DT" DESC) AS rn from all_stores)
	INSERT INTO BL_3NF.CE_STORES (
    "STORE_ID",
    "STORE_SRC_ID",
    "CITY_ID",
	  "WEBSITE",
    "STORE_DESC",
    "STORE_ADDRESS",
    "STORE_TYPE",
    "TA_INSERT_DT",
    "SOURCE_SYSTEM",
    "SOURCE_ENTITY")
SELECT 
    NEXTVAL('BL_3NF.CE_STORES_SEQ'),
    S."STORE_ID",
    COALESCE(CI."CITY_ID", -1),
	  S."WEBSITE",
    S."STORE_DESC",
    S."STORE_ADDRESS",
    S."STORE_TYPE",
    CURRENT_TIMESTAMP,
    S."SOURCE_SYSTEM",
    S."SOURCE_ENTITY"
FROM latest_stores S
LEFT JOIN BL_3NF.CE_CITIES CI 
    ON CI."CITY_SRC_ID" = S."STORE_CITY" || ' | ' || S."STORE_COUNTRY"
    AND CI."SOURCE_ENTITY"=S."SOURCE_ENTITY" AND CI."SOURCE_SYSTEM" = S."SOURCE_SYSTEM"
where S.rn =1
ON CONFLICT("STORE_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY") DO 
update set  
"CITY_ID"=excluded."CITY_ID",
"WEBSITE"=excluded."WEBSITE",
"STORE_DESC"=excluded."STORE_DESC",
"STORE_ADDRESS"=excluded."STORE_ADDRESS",
"STORE_TYPE"=excluded."STORE_TYPE"

where 
BL_3NF.CE_STORES."CITY_ID" is distinct from excluded."CITY_ID" or
BL_3NF.CE_STORES."WEBSITE" is distinct from excluded."WEBSITE" or
BL_3NF.CE_STORES."STORE_DESC" is distinct from excluded."STORE_DESC" or
BL_3NF.CE_STORES."STORE_ADDRESS" is distinct from excluded."STORE_ADDRESS" or
BL_3NF.CE_STORES."STORE_TYPE" is distinct from excluded."STORE_TYPE";
GET DIAGNOSTICS ROWS_INSERTED = ROW_COUNT;
      CALL BL_CL.LOG_ETL('LOAD_CE_STORES', ROWS_INSERTED, 'SUCCESS');
EXCEPTION  WHEN OTHERS THEN
       CALL BL_CL.LOG_ETL('LOAD_CE_STORES', 0, 'ERROR: ' || SQLERRM);
END;
$$;