CREATE OR REPLACE PROCEDURE BL_CL.LOAD_CE_JOBS()
LANGUAGE PLPGSQL
AS
$$
DECLARE ROWS_INSERTED INTEGER:=0;
BEGIN
	INSERT INTO BL_3NF.CE_JOBS (
    "JOB_ID",
    "JOB_SRC_ID",
    "JOB_DESC",
    "TA_INSERT_DT",
    "SOURCE_SYSTEM",
    "SOURCE_ENTITY")
SELECT 
    NEXTVAL('BL_3NF.CE_JOBS_SEQ'),
    J."STAFF_JOB_DESC",
    J."STAFF_JOB_DESC",
    CURRENT_TIMESTAMP,
    'SA_OFFLINE_SALES',
    'SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS'
FROM (
    SELECT DISTINCT "STAFF_JOB_DESC" AS "STAFF_JOB_DESC"
    FROM SA_OFFLINE_SALES.SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS
) J
ON CONFLICT ("JOB_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY") DO NOTHING;
GET DIAGNOSTICS ROWS_INSERTED = ROW_COUNT;
      CALL BL_CL.LOG_ETL('LOAD_CE_JOBS', ROWS_INSERTED, 'SUCCESS');
EXCEPTION  WHEN OTHERS THEN
       CALL BL_CL.LOG_ETL('LOAD_CE_JOBS', 0, 'ERROR: ' || SQLERRM);
END;
$$;
