CREATE OR REPLACE PROCEDURE BL_CL.LOAD_CE_COUNTRIES()
LANGUAGE PLPGSQL AS
$$
DECLARE
    REC RECORD;
    ROWS_INSERTED INT := 0;
BEGIN
    FOR REC IN SELECT * FROM BL_CL.FNC_GET_COUNTRIES() LOOP
        BEGIN
            INSERT INTO BL_3NF.CE_COUNTRIES (
                "COUNTRY_ID",
                "COUNTRY_SRC_ID",
                "COUNTRY_DESC",
                "TA_INSERT_DT",
                "SOURCE_SYSTEM",
                "SOURCE_ENTITY")
            VALUES (NEXTVAL('BL_3NF.CE_COUNTRIES_SEQ'),
                REC.COUNTRY_SRC_ID,
                REC.COUNTRY_DESC,
                CURRENT_TIMESTAMP,
                REC.SOURCE_SYSTEM,
                REC.SOURCE_ENTITY)
            ON CONFLICT ("COUNTRY_SRC_ID", "SOURCE_SYSTEM", "SOURCE_ENTITY") DO NOTHING;
            IF FOUND THEN
                ROWS_INSERTED := ROWS_INSERTED + 1;
            END IF;
        EXCEPTION WHEN OTHERS THEN
        CALL BL_CL.LOG_ETL('LOAD_CE_COUNTRIES', 0, 'ERROR: ' || SQLERRM);
        RAISE;
    END;
    END LOOP;
    CALL BL_CL.LOG_ETL('LOAD_CE_COUNTRIES', ROWS_INSERTED, 'SUCCESS');
END;
$$;
