CREATE OR REPLACE PROCEDURE BL_CL.LOAD_CE_STAFF_STORES()
LANGUAGE PLPGSQL
AS $$
DECLARE ROWS_INSERTED INTEGER:=0;
BEGIN
	INSERT INTO BL_3NF.CE_STAFF_STORES (
    "STAFF_STORE_ID",
    "STAFF_STORE_SRC_ID",
    "STAFF_ID",
    "STORE_ID",
    "TA_INSERT_DT",
    "SOURCE_SYSTEM",
    "SOURCE_ENTITY"
)
SELECT 
    NEXTVAL('BL_3NF.CE_STAFF_STORES_SEQ'),
    SS."STAFF_ID"|| ' | ' || SS."STORE_ID",
    COALESCE(S."STAFF_ID", -1),
    COALESCE(ST."STORE_ID", -1),
    CURRENT_TIMESTAMP,
    'SA_OFFLINE_SALES',
    'SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS'
FROM (
    SELECT DISTINCT 
        "STAFF_ID",
        "STORE_ID"
    FROM SA_OFFLINE_SALES.SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS
) SS
LEFT JOIN BL_3NF.CE_STAFF S ON S."STAFF_SRC_ID" = SS."STAFF_ID"
LEFT JOIN BL_3NF.CE_STORES ST ON ST."STORE_SRC_ID" = SS."STORE_ID"
ON CONFLICT ("STAFF_STORE_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY") DO nothing;
GET DIAGNOSTICS ROWS_INSERTED = ROW_COUNT;
      CALL BL_CL.LOG_ETL('LOAD_CE_STAFF_STORES', ROWS_INSERTED, 'SUCCESS');
EXCEPTION  WHEN OTHERS THEN
       CALL BL_CL.LOG_ETL('LOAD_CE_STAFF_STORES', 0, 'ERROR: ' || SQLERRM);
END;
$$;
