CREATE OR REPLACE PROCEDURE  BL_CL.LOAD_CE_PRODUCT_TYPES()
LANGUAGE PLPGSQL
AS
$$
DECLARE
    ROWS_INSERTED INTEGER := 0;
BEGIN 
	INSERT INTO BL_3NF.CE_PRODUCT_TYPES (
    "PRODUCT_TYPE_ID",
    "PRODUCT_TYPE_SRC_ID",
    "PRODUCT_CATEGORY_ID" ,
    "PRODUCT_TYPE_DESC",
    "TA_INSERT_DT" ,
    "SOURCE_SYSTEM",
    "SOURCE_ENTITY")
SELECT 
    NEXTVAL('BL_3NF.CE_PRODUCT_TYPES_SEQ'),
  	PT."PRODUCT_TYPE_SRC_ID",
    COALESCE(PC."PRODUCT_CATEGORY_ID", -1),
    PT."PRODUCT_TYPE",
    CURRENT_TIMESTAMP,
    PT."SOURCE_SYSTEM",
    PT."SOURCE_ENTITY"
FROM (
    SELECT DISTINCT
       "PRODUCT_TYPE" AS "PRODUCT_TYPE",
       "PRODUCT_CATEGORY" AS "PRODUCT_CATEGORY",
       "PRODUCT_TYPE"|| ' | ' || "PRODUCT_CATEGORY" || ' | ' || "PRODUCT_GROUP" AS "PRODUCT_TYPE_SRC_ID",
       "PRODUCT_GROUP" AS "PRODUCT_GROUP",
        'SA_ONLINE_SALES' AS "SOURCE_SYSTEM",
        'SRC_ONLINE_COFFEE_SHOP_TRANSACTIONS' AS "SOURCE_ENTITY"
    FROM SA_ONLINE_SALES.SRC_ONLINE_COFFEE_SHOP_TRANSACTIONS
    UNION ALL
    SELECT DISTINCT
       "PRODUCT_TYPE" AS "PRODUCT_TYPE",
       "PRODUCT_CATEGORY" AS "PRODUCT_CATEGORY",
       "PRODUCT_TYPE" || ' | ' || "PRODUCT_CATEGORY" || ' | ' || "PRODUCT_GROUP" AS "PRODUCT_TYPE_SRC_ID",
       "PRODUCT_GROUP" AS "PRODUCT_GROUP",
        'SA_OFFLINE_SALES' AS "SOURCE_SYSTEM",
        'SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS' AS "SOURCE_ENTITY"
    FROM SA_OFFLINE_SALES.SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS
) PT
LEFT JOIN BL_3NF.CE_PRODUCT_CATEGORIES PC 
ON PC."PRODUCT_CATEGORY_SRC_ID" =PT."PRODUCT_CATEGORY"|| ' | ' || PT."PRODUCT_GROUP" AND PC."SOURCE_SYSTEM"=PT."SOURCE_SYSTEM" AND PC."SOURCE_ENTITY"=PT."SOURCE_ENTITY"
ON CONFLICT("PRODUCT_TYPE_SRC_ID","SOURCE_ENTITY","SOURCE_SYSTEM") DO 
NOTHING;
GET DIAGNOSTICS ROWS_INSERTED = ROW_COUNT;
 CALL BL_CL.LOG_ETL('LOAD_CE_PRODUCT_TYPES', ROWS_INSERTED, 'SUCCESS');
EXCEPTION  WHEN OTHERS THEN
           CALL BL_CL.LOG_ETL('LOAD_CE_PRODUCT_TYPES', 0, 'ERROR: ' || SQLERRM);
END;
$$;
