CREATE OR REPLACE PROCEDURE BL_CL.LOAD_CE_PAYMENTS()
LANGUAGE PLPGSQL
AS $$
DECLARE ROWS_INSERTED INTEGER:=0;
BEGIN
	INSERT INTO BL_3NF.CE_PAYMENTS (
    "PAYMENT_ID",
    "PAYMENT_SRC_ID",
    "PAYMENT_PROVIDER_ID",
    "PAYMENT_METHOD_ID",
    "TRANSACTION_FEE",
    "TA_INSERT_DT",
    "SOURCE_SYSTEM",
    "SOURCE_ENTITY") 
SELECT 
    NEXTVAL('BL_3NF.CE_PAYMENTS_SEQ'),
    P."PAYMENT_ID"::BIGINT,
    COALESCE(PP."PAYMENT_PROVIDER_ID", -1),
    COALESCE(PM."PAYMENT_METHOD_ID", -1),
    P."TRANSACTION_FEE":: DECIMAL(8,2),
    CURRENT_TIMESTAMP,
    P."SOURCE_SYSTEM",
    P."SOURCE_ENTITY"
FROM (SELECT DISTINCT
			"PAYMENT_ID" AS "PAYMENT_ID",
			"TRANSACTION_FEE" AS "TRANSACTION_FEE",
			"PAYMENT_PROVIDER" AS "PAYMENT_PROVIDER",
			"PAYMENT_METHOD" AS "PAYMENT_METHOD",
			'SA_OFFLINE_SALES' AS "SOURCE_SYSTEM",
  			'SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS' AS "SOURCE_ENTITY"
  	FROM SA_OFFLINE_SALES.SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS 
  	UNION ALL 
	SELECT DISTINCT 
			"PAYMENT_ID" AS "PAYMENT_ID",
			"TRANSACTION_FEE_RATE" AS "TRANSACTION_FEE",
			"PAYMENT_PROVIDER" AS "PAYMENT_PROVIDER",
			"PAYMENT_METHOD" AS "PAYMENT_METHOD",
			'SA_ONLINE_SALES' AS "SOURCE_SYSTEM",
  			'SRC_ONLINE_COFFEE_SHOP_TRANSACTIONS' AS "SOURCE_ENTITY"
  	FROM SA_ONLINE_SALES.SRC_ONLINE_COFFEE_SHOP_TRANSACTIONS ) P
LEFT JOIN BL_3NF.CE_PAYMENT_PROVIDERS PP 
    ON LOWER(PP."PAYMENT_PROVIDER_SRC_ID") = LOWER(P."PAYMENT_PROVIDER")
    AND PP."SOURCE_SYSTEM"=P."SOURCE_SYSTEM" AND PP."SOURCE_ENTITY"=P."SOURCE_ENTITY" 
    LEFT JOIN BL_3NF.CE_PAYMENT_METHODS PM 
    ON LOWER(PM."PAYMENT_METHOD_SRC_ID") = LOWER(P."PAYMENT_METHOD")
     AND PM."SOURCE_SYSTEM"=P."SOURCE_SYSTEM" AND PM."SOURCE_ENTITY"=P."SOURCE_ENTITY"
ON CONFLICT("PAYMENT_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY") DO NOTHING;
GET DIAGNOSTICS ROWS_INSERTED = ROW_COUNT;
      CALL BL_CL.LOG_ETL('LOAD_CE_PAYMENTS', ROWS_INSERTED, 'SUCCESS');
EXCEPTION  WHEN OTHERS THEN
       CALL BL_CL.LOG_ETL('LOAD_CE_PAYMENTS', 0, 'ERROR: ' || SQLERRM);
END;
$$;
