CREATE OR REPLACE PROCEDURE BL_CL.LOG_ETL(
    P_PROCEDURE_NAME VARCHAR,
    P_ROWS_AFFECTED INT,
    P_MESSAGE TEXT)
LANGUAGE PLPGSQL 
AS
$$
BEGIN
    INSERT INTO BL_CL.ETL_LOG(ID,PROCEDURE_NAME, ROWS_AFFECTED, MESSAGE)
    VALUES (NEXTVAL('BL_CL.ETL_LOG_SEQ'),P_PROCEDURE_NAME, P_ROWS_AFFECTED, P_MESSAGE);
END;
$$;
COMMIT;
