CREATE OR REPLACE PROCEDURE BL_CL.LOG_ETL_DM(
    P_PROCEDURE_NAME VARCHAR,
    P_ROWS_AFFECTED INT,
    P_MESSAGE TEXT)
LANGUAGE PLPGSQL AS
$$
BEGIN
    INSERT INTO BL_CL.ETL_LOG_DM(ID, PROCEDURE_NAME, ROWS_AFFECTED, MESSAGE)
    VALUES (NEXTVAL('BL_CL.ETL_LOG_DM_SEQ'), P_PROCEDURE_NAME, P_ROWS_AFFECTED, P_MESSAGE);
END;
$$
