CREATE TABLE IF NOT EXISTS BL_DM.DIM_DATES (
	"DATE_ID" BIGINT PRIMARY KEY, -- FOR EXAMPLE 20240701 IS FOR 2024-07-01
	"DAY_OF_WEEK" VARCHAR(255) NOT NULL, -- MONDAY, THUESDAY...
	"DAY_OF_MONTH" INT NOT NULL, -- 1,2,3,4,..,,31
	"WEEK_ID" BIGINT NOT NULL, --202414 14TH WEEK OF 2024
	"MONTH_ID" BIGINT NOT NULL, --202407 FOR JULY 2024 YEAR
	"MONTH_DESC" VARCHAR(255) NOT NULL, -- JULE,JUNE etc
	"QUARTER_ID" INT NOT NULL, --1,2,3,4
	"QUARTER_DESC" VARCHAR(255) NOT NULL, --Q1,Q2,Q3,Q4
	"YEAR_ID" BIGINT NOT NULL,--2024 2023 FOR EXAMPLE
	"IS_WEEKEND" BOOLEAN NOT NULL --IF ITS WEEKEND THE VALUE IS TRUE OTHERWISE FALSE
	);
	COMMIT;
--DEFAULT ROW
INSERT INTO  BL_DM.DIM_DATES
SELECT -1,'n.a.',-1,-1,-1,'n.a.',-1,'n.a.',-1,FALSE
WHERE NOT EXISTS (SELECT 1 FROM  BL_DM.DIM_DATES WHERE "DATE_ID"=-1);
