CREATE SEQUENCE IF NOT EXISTS BL_DM.DIM_PRODUCTS_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_DM.DIM_PRODUCTS (
    "PRODUCT_SURR_ID" BIGINT PRIMARY KEY,
    "PRODUCT_SOURCE_ID" BIGINT NOT NULL,
    "PRODUCT_DESC" VARCHAR(150) NOT NULL,
    "PRODUCT_TYPE_ID" BIGINT NOT NULL,
    "PRODUCT_TYPE_DESC" VARCHAR(150) NOT NULL,
    "PRODUCT_CATEGORY_ID" BIGINT NOT NULL,
    "PRODUCT_CATEGORY_DESC" VARCHAR(200) NOT NULL,
    "PRODUCT_GROUP_ID" BIGINT NOT NULL,
    "PRODUCT_GROUP_DESC" VARCHAR(200) NOT NULL,
    "PROMO_FLAG" BOOLEAN NOT NULL,
    "PROMO_DISCOUNT" DECIMAL(6,2) NOT NULL,
    "BASE_PRICE" DECIMAL(12,2) NOT NULL,
    "IS_LIMITED_EDITION" BOOLEAN NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "TA_UPDATE_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(150) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(150) NOT NULL);
    COMMIT;
    ALTER TABLE IF EXISTS BL_DM.DIM_PRODUCTS
    DROP CONSTRAINT IF EXISTS  unique_products_source_triplet;
    ALTER TABLE IF EXISTS BL_DM.DIM_PRODUCTS
    ADD CONSTRAINT  unique_products_source_triplet
    UNIQUE("PRODUCT_SOURCE_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
       --DEFAULT ROW
    INSERT INTO BL_DM.DIM_PRODUCTS
    SELECT -1,-1,'n.a.',-1,'n.a',-1, 'n.a.', -1,'n.a.',FALSE,-1,-1,FALSE,'1900-01-01'::timestamp,'1900-01-01'::timestamp,'MANUAL','MANUAL'
    WHERE NOT EXISTS(SELECT 1 FROM BL_DM.DIM_PRODUCTS WHERE "PRODUCT_SURR_ID"=-1 );
	COMMIT;
