CREATE SEQUENCE IF NOT EXISTS BL_DM.DIM_STORES_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_DM.DIM_STORES(
    "STORE_SURR_ID" BIGINT PRIMARY KEY,
    "STORE_SOURCE_ID" BIGINT NOT NULL,
    "STORE_DESC" VARCHAR(150) NOT NULL,
    "WEBSITE" VARCHAR(150) NOT NULL,
    "CITY_ID" BIGINT NOT NULL,
    "CITY_DESC" VARCHAR(255) NOT NULL,
    "COUNTRY_ID" BIGINT NOT NULL,
    "COUNTRY_DESC" VARCHAR(100) NOT NULL,
    "STORE_ADDRESS" VARCHAR(255) NOT NULL,
    "STORE_TYPE" VARCHAR(100) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "TA_UPDATE_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(150) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(150) NOT NULL
    );
    COMMIT;
    ALTER TABLE IF EXISTS BL_DM.DIM_STORES
    DROP CONSTRAINT IF  EXISTS unique_stores_source_triplet;
    ALTER TABLE IF EXISTS BL_DM.DIM_STORES
    ADD CONSTRAINT unique_stores_source_triplet
    UNIQUE("STORE_SOURCE_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
    --DEFAULT ROW
   INSERT INTO BL_DM.DIM_STORES
   SELECT -1,-1,'n.a','n.a.',-1,'n.a',-1,'n.a','n.a','n.a','1900-01-01'::timestamp,'1900-01-01'::timestamp,'MANUAL','MANUAL'
   WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_STORES WHERE "STORE_SURR_ID" =-1);
   COMMIT;
