CREATE SEQUENCE IF NOT EXISTS BL_DM.DIM_STAFF_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_DM.DIM_STAFF(
    "STAFF_SURR_ID" BIGINT PRIMARY KEY,
    "STAFF_SOURCE_ID" BIGINT  NOT NULL,
    "STAFF_FIRST_NAME" VARCHAR(255) NOT NULL,
    "STAFF_LAST_NAME" VARCHAR(255) NOT NULL,
    "JOB_START_DT" DATE NOT NULL,
    "EMPLOYMENT_STATUS" VARCHAR(255) NOT NULL,
    "HOURLY_WAGE" DECIMAL(10,2) NOT NULL,  
    "JOB_ID" BIGINT NOT NULL,
    "JOB_DESC" VARCHAR(255) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "TA_UPDATE_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(255) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(255) NOT NULL);
   COMMIT;
   ALTER TABLE IF EXISTS BL_DM.DIM_STAFF
    DROP CONSTRAINT IF EXISTS  unique_staff_source_triplet;
   ALTER TABLE IF EXISTS BL_DM.DIM_STAFF
    ADD CONSTRAINT  unique_staff_source_triplet
    UNIQUE("STAFF_SOURCE_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
  --DEFAULT ROW
   INSERT INTO BL_DM.DIM_STAFF
   SELECT -1,-1,'n.a.','n.a.','1900-01-01'::date,'n.a.',-1,-1,'n.a.','1900-01-01'::timestamp,'1900-01-01'::timestamp,'MANUAL','MANUAL'
   WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_STAFF WHERE "STAFF_SURR_ID" =-1);
   COMMIT ;
