 CREATE SEQUENCE IF NOT EXISTS BL_DM.DIM_CUSTOMERS_SCD_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_DM.DIM_CUSTOMERS_SCD(
    "CUSTOMER_SURR_ID" BIGINT PRIMARY KEY,
    "CUSTOMER_SOURCE_ID" BIGINT  NOT NULL,
    "CUSTOMER_FIRST_NAME" VARCHAR(150) NOT NULL,
    "CUSTOMER_LAST_NAME" VARCHAR(150) NOT NULL,
    "COUNTRY_ID" BIGINT NOT NULL,
    "COUNTRY_DESC" VARCHAR(100) NOT NULL,
    "LOYALTY_MEMBER" BOOLEAN NOT NULL,
    "LOYALTY_DISCOUNT" DECIMAL(8,2) NOT NULL,
    "GENDER" VARCHAR(15) NOT NULL,
    "BIRTH_YEAR" INT NOT NULL,
    "SIGNUP_DT" DATE NOT NULL,
    "START_DT" TIMESTAMP NOT NULL,
    "END_DT" TIMESTAMP NOT NULL,
    "IS_ACTIVE" BOOLEAN NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "TA_UPDATE_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(150) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(150) NOT NULL);
     COMMIT;
    ALTER TABLE IF EXISTS BL_DM.DIM_CUSTOMERS_SCD
    DROP CONSTRAINT IF EXISTS  unique_customers_scd_source_triplet;
    ALTER TABLE IF EXISTS BL_DM.DIM_CUSTOMERS_SCD
    ADD CONSTRAINT  unique_customers_scd_source_triplet
    UNIQUE("CUSTOMER_SOURCE_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
--default row
  	 INSERT INTO BL_DM.DIM_CUSTOMERS_SCD
	 SELECT -1,-1,'n.a.','n.a.',-1,'n.a.',FALSE,-1,'n.a.',-1,'1900-01-01'::DATE,'1900-01-01'::timestamp,'9999-01-01'::timestamp,TRUE,'1900-01-01'::timestamp,'1900-01-01'::timestamp,'MANUAL','MANUAL'
	 WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_CUSTOMERS_SCD WHERE "CUSTOMER_SURR_ID" =-1);
  	 COMMIT;
