  CREATE SEQUENCE IF NOT EXISTS BL_DM.DIM_PAYMENTS_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_DM.DIM_PAYMENTS(
    "PAYMENT_SURR_ID" BIGINT PRIMARY KEY,
    "PAYMENT_SOURCE_ID" BIGINT NOT NULL,
    "PAYMENT_METHOD_ID" BIGINT NOT NULL,
    "PAYMENT_METHOD_DESC" VARCHAR(255) NOT NULL,
    "PAYMENT_PROVIDER_ID" BIGINT NOT NULL,
    "PAYMENT_PROVIDER_DESC" VARCHAR(255) NOT NULL,
    "TRANSACTION_FEE" DECIMAL(8,2) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "TA_UPDATE_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(255) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(255) NOT NULL
    );
     COMMIT;
    ALTER TABLE IF EXISTS BL_DM.DIM_PAYMENTS
    DROP CONSTRAINT IF EXISTS  unique_payments_source_triplet;
   ALTER TABLE IF EXISTS BL_DM.DIM_PAYMENTS
    ADD CONSTRAINT  unique_payments_source_triplet
    UNIQUE("PAYMENT_SOURCE_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
	 INSERT INTO BL_DM.DIM_PAYMENTS
	 SELECT -1,-1,-1,'n.a.',-1,'n.a.',-1,'1900-01-01'::timestamp,'1900-01-01'::timestamp,'MANUAL','MANUAL'
	 WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_PAYMENTS WHERE "PAYMENT_SURR_ID" =-1);
	 COMMIT;
