CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_CITIES_SEQ START 1;
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CITIES(
    "CITY_ID" BIGINT PRIMARY KEY,
    "CITY_SRC_ID" VARCHAR(100) NOT NULL,
    "COUNTRY_ID" BIGINT NOT NULL,
    "CITY_DESC" VARCHAR(100) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(150) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(150) NOT NULL,
    FOREIGN KEY("COUNTRY_ID") REFERENCES BL_3NF.CE_COUNTRIES("COUNTRY_ID"));
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_CITIES
    DROP CONSTRAINT IF EXISTS unique_cities_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_CITIES
    ADD CONSTRAINT unique_cities_source_triplet
    UNIQUE("CITY_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
    --DEFAULT ROW
   INSERT INTO BL_3NF.CE_CITIES
   SELECT -1,-1,-1,'n.a','1900-01-01'::timestamp,'MANUAL','MANUAL'
   WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_CITIES WHERE "CITY_ID" =-1);
   COMMIT;
