CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_COUNTRIES_SEQ START 1;
CREATE TABLE IF NOT EXISTS BL_3NF.CE_COUNTRIES(
    "COUNTRY_ID" BIGINT PRIMARY KEY,
    "COUNTRY_SRC_ID" VARCHAR(255) NOT NULL,
    "COUNTRY_DESC" VARCHAR(255) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(255) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(255) NOT NULL);
	COMMIT;
	ALTER TABLE IF EXISTS BL_3NF.CE_COUNTRIES
    DROP CONSTRAINT IF EXISTS unique_countries_source_triplet;
 	ALTER TABLE IF EXISTS BL_3NF.CE_COUNTRIES
    ADD CONSTRAINT unique_countries_source_triplet
    UNIQUE("COUNTRY_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
--DEFAULT ROW
   INSERT INTO BL_3NF.CE_COUNTRIES
   SELECT -1,'n.a','n.a','1900-01-01'::timestamp,'MANUAL','MANUAL'
   WHERE NOT EXISTS(SELECT 1 FROM BL_3NF.CE_COUNTRIES WHERE "COUNTRY_ID"=-1);
	COMMIT;
