 CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_CUSTOMERS_SEQ START 1;
  CREATE TABLE IF NOT EXISTS BL_3NF.CE_CUSTOMERS_SCD(
    "CUSTOMER_ID" BIGINT PRIMARY KEY,
    "CUSTOMER_SRC_ID" bigint NOT NULL,
    "CUSTOMER_FIRST_NAME" VARCHAR(255)  NOT NULL,
    "CUSTOMER_LAST_NAME" VARCHAR(255) NOT NULL,
    "COUNTRY_ID" BIGINT NOT NULL,
    "LOYALTY_MEMBER" BOOLEAN NOT NULL,
    "LOYALTY_DISCOUNT" DECIMAL(8,2) NOT NULL,
    "GENDER" VARCHAR(255) NOT NULL,
    "BIRTH_YEAR" BIGINT NOT NULL,
    "SIGNUP_DT" DATE NOT NULL,
    "START_DT" TIMESTAMP NOT NULL,
    "END_DT" TIMESTAMP NOT NULL,
    "IS_ACTIVE" BOOLEAN NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(255) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(255) NOT NULL,
    FOREIGN KEY("COUNTRY_ID") REFERENCES BL_3NF.CE_COUNTRIES("COUNTRY_ID"));
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_CUSTOMERS_SCD 
    DROP CONSTRAINT IF EXISTS unique_customers_scd_customer_id_start_dt;
    ALTER TABLE IF EXISTS BL_3NF.CE_CUSTOMERS_SCD
    ADD CONSTRAINT unique_customers_scd_customer_id_start_dt
    UNIQUE("CUSTOMER_ID","START_DT");
    COMMIT;
    --DEFAULT ROW
    INSERT INTO BL_3NF.CE_CUSTOMERS_SCD
    SELECT -1,-1,'n.a.','n.a.',-1,FALSE,-1,'n.a.',-1,'1900-01-01'::date, '1900-01-01'::timestamp,'9999-01-01'::timestamp,TRUE,'1900-01-01'::timestamp,'MANUAL','MANUAL'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_CUSTOMERS_SCD WHERE "CUSTOMER_ID" =-1);
	COMMIT; 
