CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_JOBS_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_3NF.CE_JOBS(
    "JOB_ID" BIGINT PRIMARY KEY,
    "JOB_SRC_ID" VARCHAR(255) NOT NULL,
    "JOB_DESC" VARCHAR(255) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(255) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(255) NOT NULL);
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_JOBS
    DROP CONSTRAINT IF EXISTS unique_jobs_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_JOBS
    ADD CONSTRAINT unique_jobs_source_triplet
    UNIQUE("JOB_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
      --DEFAULT ROW
   INSERT INTO BL_3NF.CE_JOBS
   SELECT -1,'n.a','n.a','1900-01-01'::timestamp,'MANUAL','MANUAL'
   WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_JOBS WHERE "JOB_ID" =-1);
	COMMIT;
    
