    CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_PRODUCT_TYPES_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCT_TYPES(
    "PRODUCT_TYPE_ID" BIGINT PRIMARY KEY,
    "PRODUCT_TYPE_SRC_ID" VARCHAR(255) NOT NULL,
    "PRODUCT_CATEGORY_ID" BIGINT NOT NULL,
    "PRODUCT_TYPE_DESC" VARCHAR(255) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(255) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(255) NOT NULL,
    FOREIGN KEY("PRODUCT_CATEGORY_ID") REFERENCES BL_3NF.CE_PRODUCT_CATEGORIES("PRODUCT_CATEGORY_ID")
    );
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_PRODUCT_TYPES
    DROP CONSTRAINT IF EXISTS unique_product_types_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_PRODUCT_TYPES
    ADD CONSTRAINT unique_product_types_source_triplet
    UNIQUE("PRODUCT_TYPE_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
    --DEFAULT ROW
    INSERT INTO BL_3NF.CE_PRODUCT_TYPES
    SELECT -1,'n.a',-1,'n.a','1900-01-01'::timestamp,'MANUAL','MANUAL'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PRODUCT_TYPES WHERE  "PRODUCT_TYPE_ID" =-1 );
	COMMIT;
