CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_PAYMENT_METHODS_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENT_METHODS(
    "PAYMENT_METHOD_ID" BIGINT PRIMARY KEY,
    "PAYMENT_METHOD_SRC_ID" VARCHAR(255) NOT NULL,
    "PAYMENT_METHOD_DESC" VARCHAR(255) NOT NULL,
    "IS_CONTACTLESS" BOOLEAN NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(255) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(255) NOT NULL);
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_PAYMENT_METHODS
    DROP CONSTRAINT IF EXISTS unique_payment_methods_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_PAYMENT_METHODS
    ADD CONSTRAINT unique_payment_methods_source_triplet
    UNIQUE("PAYMENT_METHOD_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
    --DEFAULT ROW
   INSERT INTO BL_3NF.CE_PAYMENT_METHODS
   SELECT -1,'n.a.','n.a.',TRUE,'1900-01-01'::timestamp,'MANUAL','MANUAL'
   WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PAYMENT_METHODS WHERE "PAYMENT_METHOD_ID" =-1);
	COMMIT;
