    CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_PRODUCT_CATEGORIES_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCT_CATEGORIES(
    "PRODUCT_CATEGORY_ID" BIGINT PRIMARY KEY,
    "PRODUCT_CATEGORY_SRC_ID" VARCHAR(255) NOT NULL,
    "PRODUCT_GROUP_ID" BIGINT NOT NULL,
    "PRODUCT_CATEGORY_DESC" VARCHAR(255) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(255) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(255) NOT NULL,
    FOREIGN KEY("PRODUCT_GROUP_ID") REFERENCES BL_3NF.CE_PRODUCT_GROUPS("PRODUCT_GROUP_ID")
    );
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_PRODUCT_CATEGORIES
    DROP CONSTRAINT IF EXISTS unique_product_categories_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_PRODUCT_CATEGORIES
    ADD CONSTRAINT unique_product_categories_source_triplet
    UNIQUE("PRODUCT_CATEGORY_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
    --DEFAULT ROW
	INSERT INTO BL_3NF.CE_PRODUCT_CATEGORIES
    SELECT -1,'n.a',-1,'n.a','1900-01-01'::timestamp,'MANUAL','MANUAL'
    WHERE NOT EXISTS(SELECT 1 FROM BL_3NF.CE_PRODUCT_CATEGORIES WHERE "PRODUCT_CATEGORY_ID"=-1) ;
	COMMIT;
