CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_PAYMENTS_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENTS(
    "PAYMENT_ID" BIGINT PRIMARY KEY,
    "PAYMENT_SRC_ID" BIGINT NOT NULL,
    "PAYMENT_PROVIDER_ID" BIGINT NOT NULL,
    "PAYMENT_METHOD_ID" BIGINT NOT NULL,
    "TRANSACTION_FEE" DECIMAL(8,2) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(255) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(255) NOT NULL,
    FOREIGN KEY("PAYMENT_PROVIDER_ID") REFERENCES BL_3NF.CE_PAYMENT_PROVIDERS("PAYMENT_PROVIDER_ID"),
    FOREIGN KEY("PAYMENT_METHOD_ID") REFERENCES BL_3NF.CE_PAYMENT_METHODS("PAYMENT_METHOD_ID"));
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_PAYMENTS
    DROP CONSTRAINT IF EXISTS unique_payments_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_PAYMENTS
    ADD CONSTRAINT unique_payments_source_triplet
    UNIQUE("PAYMENT_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
        --DEFAULT ROW
 INSERT INTO BL_3NF.CE_PAYMENTS
 SELECT -1,-1,-1,-1,-1,'1900-01-01'::timestamp,'MANUAL','MANUAL'
 WHERE NOT EXISTS (SELECT * FROM BL_3NF.CE_PAYMENTS WHERE "PAYMENT_ID" =-1);
 COMMIT;
    
