CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_PAYMENT_PROVIDERS_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENT_PROVIDERS(
    "PAYMENT_PROVIDER_ID" BIGINT PRIMARY KEY,
    "PAYMENT_PROVIDER_SRC_ID" VARCHAR(100) NOT NULL,
    "PAYMENT_PROVIDER_DESC" VARCHAR(100) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(150) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(150) NOT NULL);
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_PAYMENT_PROVIDERS
    DROP CONSTRAINT IF EXISTS unique_payment_provider_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_PAYMENT_PROVIDERS
    ADD CONSTRAINT unique_payment_provider_source_triplet
    UNIQUE("PAYMENT_PROVIDER_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
        --DEFAULT ROW
INSERT INTO BL_3NF.CE_PAYMENT_PROVIDERS
SELECT -1,'n.a.','n.a','1900-01-01'::timestamp,'MANUAL','MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PAYMENT_PROVIDERS WHERE "PAYMENT_PROVIDER_ID" =-1);
COMMIT;
