CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_PRODUCTS_SEQ START 1;
   CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCTS(
    "PRODUCT_ID" BIGINT PRIMARY KEY,
    "PRODUCT_SRC_ID" bigint NOT NULL,
    "PRODUCT_TYPE_ID" BIGINT NOT NULL,
    "PRODUCT_DESC" VARCHAR(255) NOT NULL,
    "PROMO_FLAG" BOOLEAN NOT NULL,
    "PROMO_DISCOUNT" DECIMAL(6,2) NOT NULL,
    "BASE_PRICE" DECIMAL(12,2) NOT NULL,
    "IS_LIMITED_EDITION" BOOLEAN NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(255) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(255) NOT NULL,
    FOREIGN KEY("PRODUCT_TYPE_ID") REFERENCES BL_3NF.CE_PRODUCT_TYPES("PRODUCT_TYPE_ID")
    );
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_PRODUCTS
    DROP CONSTRAINT IF EXISTS unique_products_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_PRODUCTS
    ADD CONSTRAINT unique_products_source_triplet
    UNIQUE("PRODUCT_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
    --DEFAULT ROW
    INSERT INTO BL_3NF.CE_PRODUCTS
    SELECT -1,-1,-1,'n.a',FALSE,-1,-1,FALSE,'1900-01-01'::timestamp,'MANUAL','MANUAL'
    WHERE NOT EXISTS(SELECT 1 FROM BL_3NF.CE_PRODUCTS WHERE "PRODUCT_ID"=-1 );
	COMMIT;
    
