--CE_SALES
CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_SALES_SEQ START 1;
 CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES(
    "SALE_ID" BIGINT PRIMARY KEY,
    "SALE_SRC_ID" VARCHAR(100) NOT NULL,
    "CUSTOMER_ID" BIGINT  NOT NULL,
    "STAFF_ID" BIGINT NOT NULL,
    "STORE_ID" BIGINT NOT NULL,
    "PAYMENT_ID" BIGINT NOT NULL,
    "MANAGER_ID" BIGINT NOT NULL,
    "PRODUCT_ID" BIGINT NOT NULL,
    "EVENT_DT" BIGINT NOT NULL,
    "QUANTITY" INT NOT NULL,
    "LINE_ITEM_AMOUNT" DECIMAL(8,2) NOT NULL,
    "COST" DECIMAL(8,2) NOT NULL,
    "PROFIT" DECIMAL(8,2) NOT NULL,
    "PROFIT_MARGIN" DECIMAL(8,2) NOT NULL,
    "DELIVERY_FEE" DECIMAL(8,2) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(150) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(150) NOT NULL,
    FOREIGN KEY("CUSTOMER_ID") REFERENCES BL_3NF.CE_CUSTOMERS_SCD("CUSTOMER_ID"),
    FOREIGN KEY("STAFF_ID") REFERENCES BL_3NF.CE_STAFF("STAFF_ID"),
    FOREIGN KEY("STORE_ID") REFERENCES BL_3NF.CE_STORES("STORE_ID"),
    FOREIGN KEY("MANAGER_ID") REFERENCES BL_3NF.CE_STAFF("STAFF_ID"),
    FOREIGN KEY("PAYMENT_ID") REFERENCES BL_3NF.CE_PAYMENTS("PAYMENT_ID"),
    FOREIGN KEY ("PRODUCT_ID") REFERENCES BL_3NF.CE_PRODUCTS("PRODUCT_ID"));
 	 COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_SALES
    DROP CONSTRAINT IF EXISTS unique_sales_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_SALES
    ADD CONSTRAINT unique_sales_source_triplet
    UNIQUE("SALE_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
	INSERT INTO BL_3NF.ce_sales 
	SELECT  -1,'n.a.',-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,'1900-01-01'::timestamp,'MANUAL','MANUAL'
	WHERE NOT EXISTS(SELECT 1 FROM BL_3NF.ce_sales WHERE "SALE_ID"=-1);
