 CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_STAFF_STORES_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_3NF.CE_STAFF_STORES(
    "STAFF_STORE_ID" BIGINT PRIMARY KEY,
    "STAFF_STORE_SRC_ID" VARCHAR(150) NOT NULL,
    "STAFF_ID" BIGINT NOT NULL,
    "STORE_ID" BIGINT NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(150) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(150) NOT NULL,
    FOREIGN KEY("STAFF_ID") REFERENCES BL_3NF.CE_STAFF("STAFF_ID"),
    FOREIGN KEY("STORE_ID") REFERENCES BL_3NF.CE_STORES("STORE_ID"));
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_STAFF_STORES
    DROP CONSTRAINT IF EXISTS unique_staff_stores_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_STAFF_STORES
    ADD CONSTRAINT unique_staff_stores_source_triplet
    UNIQUE("STAFF_STORE_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
    --DEFAULT ROW
    INSERT INTO BL_3NF.CE_STAFF_STORES
    SELECT -1,'n.a',-1,-1,'1900-01-01'::timestamp,'MANUAL','MANUAL'
    WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_STAFF_STORES WHERE "STAFF_STORE_ID" =-1);
    COMMIT;
