 CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_STAFF_JOBS_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_3NF.CE_STAFF_JOBS(
    "STAFF_JOB_ID" BIGINT PRIMARY KEY,
    "STAFF_JOB_SRC_ID" VARCHAR(100) NOT NULL,
    "STAFF_ID" BIGINT NOT NULL,
    "JOB_ID" BIGINT NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(150) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(150) NOT NULL,
    FOREIGN KEY("STAFF_ID") REFERENCES BL_3NF.CE_STAFF("STAFF_ID"),
    FOREIGN KEY("JOB_ID") REFERENCES BL_3NF.CE_JOBS("JOB_ID"));
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_STAFF_JOBS
    DROP CONSTRAINT IF EXISTS unique_staff_jobs_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_STAFF_JOBS
    ADD CONSTRAINT unique_staff_jobs_source_triplet
    UNIQUE("STAFF_JOB_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
	  --DEFAULT ROW
   INSERT INTO BL_3NF.CE_STAFF_JOBS
   SELECT -1,'n.a',-1,-1,'1900-01-01'::timestamp,'MANUAL','MANUAL'
   WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_STAFF_JOBS WHERE "STAFF_JOB_ID" =-1);
	COMMIT;
    
