
    CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_STORES_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_3NF.CE_STORES(
    "STORE_ID" BIGINT PRIMARY KEY,
    "STORE_SRC_ID" VARCHAR(50) NOT NULL,
    "CITY_ID" BIGINT NOT NULL,
    "WEBSITE" VARCHAR(150) NOT NULL,
    "STORE_DESC" VARCHAR(100) NOT NULL,
    "STORE_ADDRESS" VARCHAR(200) NOT NULL,
    "STORE_TYPE" VARCHAR(100) NOT NULL,
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(150) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(150) NOT NULL,
    FOREIGN KEY("CITY_ID") REFERENCES BL_3NF.CE_CITIES("CITY_ID"));
    COMMIT;
    ALTER TABLE IF EXISTS BL_3NF.CE_STORES
    DROP CONSTRAINT IF EXISTS unique_stores_source_triplet;
    ALTER TABLE IF EXISTS BL_3NF.CE_STORES
    ADD CONSTRAINT unique_stores_source_triplet
    UNIQUE("STORE_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
    --DEFAULT ROW
   INSERT INTO BL_3NF.CE_STORES
   SELECT -1,'n.a',-1,'n.a','n.a','n.a','n.a','1900-01-01'::timestamp,'MANUAL','MANUAL'
   WHERE NOT EXISTS (SELECT * FROM BL_3NF.CE_STORES WHERE "STORE_ID" =-1);
    COMMIT;
