    CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_STAFF_SEQ START 1;
    CREATE TABLE IF NOT EXISTS BL_3NF.CE_STAFF(
    "STAFF_ID" BIGINT PRIMARY KEY,
    "STAFF_SRC_ID" VARCHAR(100) NOT NULL,
    "STAFF_FIRST_NAME" VARCHAR(50) NOT NULL,
    "STAFF_LAST_NAME" VARCHAR(50) NOT NULL,
    "JOB_START_DT" DATE NOT NULL,
    "EMPLOYMENT_STATUS" VARCHAR(30) NOT NULL,
    "HOURLY_WAGE" DECIMAL(10,2) NOT NULL,    
    "TA_INSERT_DT" TIMESTAMP NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(150) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(150) NOT NULL);
    COMMIT;
	ALTER TABLE IF EXISTS BL_3NF.CE_STAFF
    DROP CONSTRAINT IF EXISTS unique_staff_source_triplet;
 	ALTER TABLE IF EXISTS BL_3NF.CE_STAFF
    ADD CONSTRAINT unique_staff_source_triplet
    UNIQUE("STAFF_SRC_ID","SOURCE_SYSTEM","SOURCE_ENTITY");
    COMMIT;
  --DEFAULT ROW
   INSERT INTO BL_3NF.CE_STAFF
   SELECT -1,'n.a','n.a','n.a','1900-01-01'::date,'n.a.',-1,'1900-01-01'::timestamp,'MANUAL','MANUAL'
   WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_STAFF WHERE "STAFF_ID" =-1);
   COMMIT;
