--FOR 3NF TABLES 
CREATE SEQUENCE IF NOT EXISTS BL_CL.ETL_LOG_SEQ START 1;
CREATE TABLE IF NOT EXISTS BL_CL.ETL_LOG (
    ID BIGINT PRIMARY KEY,
    LOG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROCEDURE_NAME TEXT,
    ROWS_AFFECTED INT,
    MESSAGE TEXT);
COMMIT;
