CREATE SEQUENCE IF NOT EXISTS BL_CL.ETL_LOG_DM_SEQ START 1;
CREATE TABLE IF NOT EXISTS BL_CL.ETL_LOG_DM (
    ID BIGINT PRIMARY KEY,
    LOG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROCEDURE_NAME TEXT,
    ROWS_AFFECTED INT,
    MESSAGE TEXT);
