CREATE TABLE IF NOT EXISTS BL_CL.t_map_customers (
    "CUSTOMER_ID" BIGINT NOT NULL,
    "CUSTOMER_SRC_FIRST_NAME" VARCHAR(1000) not NULL,
    "CUSTOMER_SRC_LAST_NAME" VARCHAR(1000) not null ,
    "CUSTOMER_SRC_ID" VARCHAR(1000) NOT NULL,
    "CUSTOMER_FIRST_NAME" VARCHAR(1000) NOT NULL,
    "CUSTOMER_LAST_NAME" VARCHAR(1000) NOT NULL,
    "SOURCE_SYSTEM" VARCHAR(255) NOT NULL,
    "SOURCE_ENTITY" VARCHAR(255) NOT NULL);
WITH all_sources AS (
  SELECT DISTINCT 
    "CUSTOMER_ID" AS "CUSTOMER_SRC_ID",
    "CUSTOMER_FIRST_NAME" AS "CUSTOMER_SRC_FIRST_NAME",
    "CUSTOMER_LAST_NAME" AS "CUSTOMER_SRC_LAST_NAME",
    TRIM(LOWER("CUSTOMER_FIRST_NAME")) AS "norm_first_name",
    TRIM(LOWER("CUSTOMER_LAST_NAME")) AS "norm_last_name",
     "EVENT_DT",
    'SA_ONLINE_SALES' AS "SOURCE_SYSTEM",
    'SRC_ONLINE_COFFEE_SHOP_TRANSACTIONS' AS "SOURCE_ENTITY"
  FROM sa_online_sales.src_online_coffee_shop_transactions
  UNION ALL
  SELECT DISTINCT 
    "CUSTOMER_ID",
    "CUSTOMER_FIRST_NAME",
    "CUSTOMER_LAST_NAME",
    TRIM(LOWER("CUSTOMER_FIRST_NAME")),
    TRIM(LOWER("CUSTOMER_LAST_NAME")),
    "EVENT_DT",
    'SA_OFFLINE_SALES',
    'SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS'
  FROM sa_offline_sales.src_offline_coffee_shop_transactions),
latest_cust AS (SELECT *,row_number() OVER (PARTITION BY "CUSTOMER_SRC_ID","SOURCE_ENTITY","SOURCE_SYSTEM" ORDER BY "EVENT_DT" DESC) AS rn FROM all_sources),
assigned_ids AS ( SELECT  ROW_NUMBER() OVER (ORDER BY "CUSTOMER_SRC_ID" ) AS "CUSTOMER_ID", "CUSTOMER_SRC_ID"
  FROM ( SELECT DISTINCT "CUSTOMER_SRC_ID" FROM latest_cust  WHERE rn =1  ) AS unique_customers )
INSERT INTO BL_CL.t_map_customers (
  "CUSTOMER_ID",
  "CUSTOMER_SRC_FIRST_NAME",
  "CUSTOMER_SRC_LAST_NAME",
  "CUSTOMER_SRC_ID",
  "CUSTOMER_FIRST_NAME",
  "CUSTOMER_LAST_NAME",
  "SOURCE_SYSTEM",
  "SOURCE_ENTITY")
SELECT 
  aid."CUSTOMER_ID",
  src."CUSTOMER_SRC_FIRST_NAME",
  src."CUSTOMER_SRC_LAST_NAME",
  src."CUSTOMER_SRC_ID",
  INITCAP(src."norm_first_name") AS "CUSTOMER_FIRST_NAME",
  INITCAP(src."norm_last_name") AS "CUSTOMER_LAST_NAME",
  src."SOURCE_SYSTEM",
  src."SOURCE_ENTITY"
FROM latest_cust src
JOIN assigned_ids aid
  ON src."CUSTOMER_SRC_ID" = aid."CUSTOMER_SRC_ID"
  WHERE src.rn=1 AND NOT EXISTS (SELECT 1 FROM BL_CL.t_map_customers WHERE "CUSTOMER_SRC_ID"=src."CUSTOMER_SRC_ID") ;
