CREATE OR REPLACE FUNCTION BL_CL.FNC_GET_COUNTRIES()
RETURNS TABLE ( COUNTRY_SRC_ID VARCHAR,
    COUNTRY_DESC VARCHAR,
    SOURCE_SYSTEM VARCHAR,
    SOURCE_ENTITY VARCHAR)
AS
$$
BEGIN
   RETURN QUERY
   SELECT DISTINCT "STORE_COUNTRY"::VARCHAR,
                    "STORE_COUNTRY"::VARCHAR,
                    'SA_ONLINE_SALES'::VARCHAR,
                    'SRC_ONLINE_COFFEE_SHOP_TRANSACTIONS'::VARCHAR
    FROM SA_ONLINE_SALES.SRC_ONLINE_COFFEE_SHOP_TRANSACTIONS
    UNION all
    SELECT DISTINCT "STORE_COUNTRY"::VARCHAR,
                    "STORE_COUNTRY"::VARCHAR,
                    'SA_OFFLINE_SALES'::VARCHAR,
                    'SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS'::VARCHAR
    FROM SA_OFFLINE_SALES.SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS
    UNION all
    SELECT DISTINCT "CUSTOMER_COUNTRY"::VARCHAR,
                    "CUSTOMER_COUNTRY"::VARCHAR,
                    'SA_OFFLINE_SALES'::VARCHAR,
                    'SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS'::VARCHAR
    FROM SA_OFFLINE_SALES.SRC_OFFLINE_COFFEE_SHOP_TRANSACTIONS
    UNION all
    SELECT DISTINCT "CUSTOMER_COUNTRY"::VARCHAR,
                    "CUSTOMER_COUNTRY"::VARCHAR,
                    'SA_ONLINE_SALES'::VARCHAR,
                    'SRC_ONLINE_COFFEE_SHOP_TRANSACTIONS'::VARCHAR
    FROM SA_ONLINE_SALES.SRC_ONLINE_COFFEE_SHOP_TRANSACTIONS;
END;
$$
LANGUAGE PLPGSQL;
